version: 0.0
os: linux

files:
  - source: ./code
    destination: /var/www/html/app/
  - source: ./design
    destination: /var/www/html/app/
    

hooks:
  BeforeInstall:
    - location: scripts/stop_nginx.sh
      runas: root
  AfterInstall:
    - location: scripts/start_nginx.sh
      timeout: 180
      runas: root
  ValidateService:
    - location: scripts/status_nginx.sh
      timeout: 3600
      runas: root
