version: 0.0
os: linux

files:
  - source: ./app
    destination: /app/magento/emimall-uat/app
  - source: ./customcron
    destination: /app/magento/emimall-uat/customcron
  - source: ./composer.json
    destination: /app/magento/emimall-uat/
  - source: ./composer.lock
    destination: /app/magento/emimall-uat/
  - source: ./vendor
    destination: /app/magento/emimall-uat/vendor


hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 3600
      runas: root

  ApplicationStart:
    - location: scripts/changepermission.sh
      timeout: 3600 
    
  hooks:
   AfterAllowTraffic:
     - location: Scripts/CodeDeployBG.sh
       timeout: 3600


  ValidateService:
    - location: scripts/status_service.sh
      timeout: 3600
      runas: root
