<?php
/*  Copyright (c) BFL (bajaj finserv limited), India  */
// @codingStandardsIgnoreFile

/**
 * Product review template
 *
 * @var $block Cybage\ImportReview\Block\Reviews
 */
?>
<?php $expertReview = $block->getExpertReview();
    $iframeVideoArray = [];
?>

<div class="expertRePdp" id="experRew4">
    <?php if (!empty($expertReview) && $expertReview['rating'] > 0) {
        
        $overallRating = $expertReview['rating'];
                
                ?>
        <div class="p_exptitle">
            <strong>Expert Reviews ( 1 )</strong>
        </div>
        <div class="reSlidemob">
            <div class="sliderreves exprtreview">
                <div class="slioneSec">
                    <div class="p_expreport">

                        <!--exprtreview-->

                        <div class="p_renewslider ">
                            <div class="p_expreviewbord">
                                <ul>
                                    <li class="nintyOneIcon"><img src="<?= $this->getViewFileUrl('images/pdp/91mob.jpg'); ?>" alt="nineone"/></li>
                                    <li>
                                        <!--<a href="javascript:void(0);">-->
                                            <div class="p_reviewpoint">
                                                <ul class="j_AllRatio">
                                                        <?php for ($i=1; $i<=5; $i++) {
                                                            $anchorclass = '';
                                                            if ($i <= $overallRating) {
                                                                $starclass = 'fas fa-star';
                                                            } elseif ($i> $overallRating && ($i-1 <$overallRating)) {
                                                                $starclass = "fas fa-star-half-o";
                                                            } else {
                                                                $anchorclass = 'j-grey';
                                                                $starclass = 'fas fa-star';
                                                            }

                                                            ?>
                                                        <li><a href="javascript:void(0);" class="<?= /* @noEscape */ $anchorclass ?>">
                                                                <i class="<?= /* @noEscape */ $starclass?>"></i>
                                                            </a>
                                                        </li>

                                                        <?php } ?>
                                                    </ul>
                                                </div>
                                        <!--</a>-->
                                    </li>
                                </ul>
                                <p class="expertRewiesTitle"><?= $expertReview['title'] ?></p>
                                <p><?= $expertReview['reviewed_date'] ?> By <?= $expertReview['reviewed_by'] ?></p>
                            </div>
                        </div>
                    </div>
                    <?php if (isset($expertReview['pros']) || isset($expertReview['Cons'])) : ?>
                        <div class="j_proConsTb">
                            <ul class="j_tbBor">
                                <li class="active"><a data-tab="j_pro1" href="javascript:void(0)">Pros</a></li>
                                <li><a data-tab="j_cons1" href="javascript:void(0)">Cons</a></li>
                            </ul>
                            <div class="j_tabFlWidth">
                                <?php if (isset($expertReview['pros'])) : ?>
                                    <div class="jTbId j_actTb" id="j_pro1">
                                        <ul>
                                            <?php foreach ($expertReview['pros'] as $pros): ?>
                                                <li><i class="fa fa-check-circle"></i> <p><?= $pros; ?></p></li>
                                            <?php endforeach; ?>
                                        </ul>
                                    </div>
                                <?php endif; ?>
                                <?php if (isset($expertReview['cons'])) : ?>
                                    <div class="jTbId" id="j_cons1">
                                        <ul>
                                            <?php foreach ($expertReview['cons'] as $cons): ?>
                                                <li><i class="fa fa-check-circle"></i> <p><?= $cons; ?></p></li>
                                            <?php endforeach; ?>
                                        </ul>
                                    </div>
                                <?php endif; ?>

                            </div>
                        </div>
                    <?php endif; ?>
                    <?php if (!empty($expertReview['verdict'])) : ?>
                        <div class="j_verText">
                            <h3>The Final Verdict</h3>
                            <p><?= $expertReview['verdict'] ?></p>
                            <a class="j_more" href="javascript:void(0)">More</a>
                        </div>
                    <?php endif ?>

                    <?php 

                    if (isset($expertReview['videos'])) : ?>
                        <div class="j_videsec">
                            <div class="j_slidSlid">
                                <?php $count = 0; ?>
                                <?php foreach ($expertReview['videos'] as $video): 
                                    if ($count < 3) {
                                        $class = "j_partVid active";
                                     } else {
                                         $class = "j_partVid inactive";
                                     }
                                     $count++; ?>
                                     <?php
                                     $videoUrl = $this->helper('Cybage\Productdetail\Helper\Data')->getYoutubeEmbedUrl($video['videoId']);
                                     $key = 'iframe_video'.$count;
                                     $iframeVideoArray[$key] = $videoUrl;
                                     ?>
                                    <div class="<?= $class ?>" data-videourl="<?= $key?>">
                                        <a href="javascript:void(0)" class="videoimg">
                                            <img src="<?= $video['videoImgUrl'] ?>" alt="vid"/>
                                            <div class="j_desVideo">
                                                <h3><?= $video['caption'] ?></h3>
                                                <p><?= $video['playback_time'] ?></p>
                                            </div>
                                        </a>
                                    </div>
                                <?php endforeach; ?>
                                <?php if($count > 3) { ?>
                                <div class="videoViewAllLink"><a href="javascript:void(0);">View All</a></div>
                                <?php } ?>
                            </div>
                        </div>
                    <?php endif; ?>

                </div>

            </div>
        </div>
    <?php } ?>
    <?php echo $block->getChildHtml('product.info.userreviews'); ?>

</div>

<div class="p_expertreviewpopup">
    <div class="p_expertreviewpopupblack">
        <div class="p_videobackground">
            <div class="p_videoarea">
                <div class="p_videoclose"><a href="javascript:void(0);"><img src="<?php echo $this->getViewFileUrl('images/closesim.png'); ?>" alt=""></a></div>
                <?php
                if(count($iframeVideoArray) > 0) {
                    foreach($iframeVideoArray as $key=>$url) { ?>
                        <iframe class="pdp_iframe" id="<?= $key ?>" src="<?= $url?>"  allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                <?php }
                }?>
            </div>
        </div>
    </div>
</div>

