<?php
/**
 * Copyright Â© Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>

<?php if ($block->canShowBlock()): ?>
    <div class="block filter" id="layered-filter-block" data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false, "collateral": { "openedState": "filter-active", "element": "body" } }}'>
        <?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
        <div class="block-title filter-title" data-count="<?= /* @escapeNotVerified */ $filtered ?>">
            <strong data-role="title">1<?= /* @escapeNotVerified */ __('Shop By') ?></strong>
        </div>
        <div class="a_filterConmain" id="SortBY">
                <div class="filter-options" data-role="content">
                    <div data-role="ln_collapsible" class="filter-options-item a_mainfilBlock" attribute="sort">
                        <div data-role="ln_title" class="filter-options-title" style="display: block;">
                            <img src="<?= $block->getViewFileUrl('images/arrow-left.png'); ?>" alt="">
                            <p><?= /* @escapeNotVerified */  __('Sort') ?></p>
                        </div>
                        <div data-role="ln_content" class="filter-options-contents a_filterCon">
                            <?php $toolbarBlock = $block->getLayout()->createBlock('Cybage\CatalogProduct\Block\Product\ProductList\Toolbar'); ?>
                            <ul class="items grayCheck">
                                <?php foreach ($toolbarBlock->getAvailableOrders() as $_key => $_order): ?>
                                <li class="item">
                                    <p>
                                        <input type="radio" id="filtes<?=  $_key ?>" name="sort" value="<?=  $_key ?>" class="layer-input-filter" <?php if ($toolbarBlock->isOrderCurrent($_key)){ ?> checked="checked" <?php } ?> />
                                        
                                         <a class="sorter-mode <?php if ($toolbarBlock->isOrderCurrent($_key)){ ?> ajaxchecked <?php } ?>"
                                         title="<?= $block->escapeHtml(__($_order)) ?>"
                                         href="#"
                                         data-role="sorter"
                                         data-value="<?=  $_key ?>"
                                         id="filtes<?=  $_key ?>"
                                         aria-labelledby="sorter-label-<?=  $_key ?>">
                                           <?= $block->escapeHtml(__($_order)) ?>
                                       </a>
                                    </p>
                                </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    </div>
                </div>
               <a href="javascript:void(0);" class="applyFilter"><?= /* @escapeNotVerified */  __('Apply') ?></a>
        </div>
        
        <div class="block-content filter-content">

            <?php $wrapOptions = false; ?>
            <?php foreach ($block->getFilters() as $filter): ?>
                <?php if ($filter->getItemsCount()): ?>
                    <?php if (!$wrapOptions): ?>
                        <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle">
                            <img src="<?= $block->getViewFileUrl('images/arrow-left.png'); ?>" alt="">
                            <?= __('Shopping Options') ?>
                        </strong>
                        <div class="filter-options" id="narrow-by-list" data-role="content" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": false}}'>
                    <?php  $wrapOptions = true; endif; ?>
                    <div data-role="collapsible" class="filter-options-item">
                        <div data-role="title" class="filter-options-title"><?= /* @escapeNotVerified */ __($filter->getName()) ?></div>
                        <div data-role="content" class="filter-options-content"><?= /* @escapeNotVerified */ $block->getChildBlock('renderer')->render($filter) ?></div>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($wrapOptions): ?>
                </div>
            <?php else: ?>
                <script>
                    require([
                        'jquery'
                    ], function ($) {
                        $('#layered-filter-block').addClass('filter-no-options');
                    });
                </script>
            <?php endif; ?>
        </div>
        <div class="applyCanclBtn">
              <a href="<?= /* @escapeNotVerified */  $block->getClearUrl() ?>" class="clearAll"><?= /* @escapeNotVerified */ __('Clear All') ?></a>
              <a href="javascript:void(0);" class="applyFilter"><?= /* @escapeNotVerified */  __('Apply') ?></a>
        </div>
    </div>
<?php endif; ?>
