<?php
$cities = $block->getAllCities();
$categories = $block->getStoreCategories(true, false, true);
$categoryHelper = $block->getCategoryHelper();
$customerData = $block->getCustomerSessionData();
$numberofStoresPerPage= $block->getNumberofStoresPerpage();
if(!isset($customerData['category_filter'])) {
    $customerData['category_filter'] = [];
}
if(!isset($customerData['group_filter'])) {
    $customerData['group_filter'] = [];
}
if(!isset($customerData['pincode_filter'])) {
    $customerData['pincode_filter'] = [];
}
$popularCities = $this->helper('Cybage\Storelocator\Helper\Category')->getPopulaCities();
$googleApiUrl = $this->helper('Cybage\Storelocator\Helper\Category')->getGoogleApiUrl();
$googleApiKey = $this->helper('Cybage\Storelocator\Helper\Category')->getGoogleApiKey();
$ipinfoApiUrl = $this->helper('Cybage\Storelocator\Helper\Category')->getIpInfoApiUrl();
if ($googleApiUrl && $googleApiKey) {
    $googleMapsApi = $googleApiUrl . $googleApiKey;
}
$geolocationApiUrl = $this->helper('Cybage\Storelocator\Helper\Category')->getGeoLocationApiUrl();

$sfdcResponse = $this->helper('Cybage\Storelocator\Helper\Sfdcapi');
$sfdc = $sfdcResponse->getSfdcforall();
?>

<input id="ipinfo-url"type="text" value="<?php echo $ipinfoApiUrl ?>" hidden="true"/>
<input id="geolocation-api-url"type="text" value="<?php echo $geolocationApiUrl ?>" hidden="true"/>
<input id="directions-icon"type="text" value="<?php echo $this->getViewFileUrl('images/ico-directio.png'); ?>" hidden="true"/>
<input id="call-icon"type="text" value="<?php echo $this->getViewFileUrl('images/ico-call-wht.svg'); ?>" hidden="true"/>
<input id="ico-call"type="text" value="<?php echo $this->getViewFileUrl('images/ico-call.svg'); ?>" hidden="true"/>
<input id="ico-call-request"type="text" value="<?php echo $this->getViewFileUrl('images/ico-call-request.svg'); ?>" hidden="true"/>
<input id="shopping-pin"type="text" value="<?php echo $this->getViewFileUrl('images/shopping-pin.png'); ?>" hidden="true"/>
<input id="selected-pin"type="text" value="<?php echo $this->getViewFileUrl('images/selected_pin.png'); ?>" hidden="true"/>

<div class="A_pageCenter">
    <section class="storelocatorsec">
        <div class="storelocatorMain">
            <div class="storelocatorLeft storelocatorLeftFull">
                <?php
                $categorycss = '';
                
                if (isset($customerData['categorylob']) && !empty($customerData['categorylob'])) {
                    $categorycss = 'lobexist';
                }
                ?>
                
                <?php
                $categorystyle = '';
                if (isset($customerData['categorylob']) && !empty($customerData['categorylob'])) {
                    $categorystyle = 'style="display:none"';
                }
                ?>
                <div class="a_lookingPart slideright" <?= $categorystyle ?>>
                    <div class="storehead">
                        <p>
                            <img src="<?php echo $this->getViewFileUrl('images/back.svg'); ?>" alt="">Select sub category
                        </p>
                    </div>
                    <div class="a_lookTitle">
                        <h4> <img src="<?php echo $this->getViewFileUrl('images/back_black.svg'); ?>" alt=""> What are you looking for?</h4>
                    </div>
                    <div class="a_lookProtab">
                        <ul>
                            <?php
                            foreach ($categories as $category) {
                                if (!$category->getIsActive()) {
                                    continue;
                                }
                                ?>
                                <li><a href="javascript:void(0);" class="" data-tab="<?= $category->getId() ?>cat"><?php echo $category->getName() ?></a></li>
                                <?php
                            }
                            ?>
                        </ul>
                    </div>
                    <div class="productInfoMainWrap">
                        <?php
                        foreach ($categories as $category) {
                            if (!$category->getIsActive()) {
                                continue;
                            }
                            if ($childrenCategories = $block->getChildCategories($category)) {
                                ?>
                                <div class="a_productInfo a_productInfoShow" id="<?= $category->getId() ?>cat">
                                    <div class="a_row8">
                                        <?php
                                        $categoryLists = [];
                                        foreach ($childrenCategories as $childrenCategory) {
                                            if (!$childrenCategory->getIsActive()) {
                                                continue;
                                            }
                                            $categoryData = $block->getCategory($childrenCategory->getId());
                                            if (empty($categoryData['icon']) || $categoryData['icon'] == '') {
                                                $childrenCategory = $childrenCategory->getData();
                                                $childrenCategory['lob'] = $categoryData['lob'];
                                                $categoryLists[] = $childrenCategory;
                                            } else {
                                                ?>
                                                <div class="a_onePro">
                                                    <a href="javascript:void(0);" class="category" data-categorylob="<?= $categoryData['lob'] ?>">
                                                        <div class="a_innerOnePro">
                                                            <img src="<?php echo $this->getUrl('pub/media') . '/catalog/category/' . $categoryData['icon']; ?>" alt="">
                                                            <p><?php echo $childrenCategory->getName() ?></p>
                                                        </div>
                                                    </a>
                                                </div>
                                                <?php
                                            }
                                        }
                                        ?>
                                    </div>
                                    <div class = "listView">
                                        <ul>
                                            <?php
                                            foreach ($categoryLists as $categoryList) {
                                                ?>
                                                <li><a href="javascript:void(0);" class="category" data-categorylob="<?= $categoryList['lob'] ?>"><?php echo $categoryList['name'] ?></a></li>
                                                <?php
                                            }
                                            ?>
                                        </ul>
                                    </div>
                                </div>
                                <?php
                            }
                        }
                        ?>
                    </div>
                </div>
                <?php
                if (isset($customerData['bfl_customer_city_name']) && !empty($customerData['bfl_customer_city_name']) && isset($customerData['categorylob']) && !empty($customerData['categorylob'])) {
                    $stores = $block->getStoreList();
                    ?>
                    <!--store-list-->
                    <div class="p_storelist slideright">
                        <div class="storehead stores-header">
                            <p>
                                <img src="<?php echo $this->getViewFileUrl('images/back.svg'); ?>" alt="">List view
                            </p>
                        </div>
                        <?php
                        if (count($stores) == 0) {
                            ?>
                            <div class="storeListzero">
                                <p class="storetitle">Store List (0)</p>
                                <div class="storezeroimg">
                                    <img src="<?php echo $this->getViewFileUrl('images/no-store.svg'); ?>" alt="store" />
                                </div>
                                <p class="storezerocntn">There aren’t any stores in this area. Try a different combination</p>
                                <div class="szopenfilter"><a href="javascript:void(0);">Open FIlters</a></div>
                            </div>
                        <?php } else {
                            ?>
                            <div class="a_storeListavail">
                                <div class="p_topborder">
                                    <div class="makenotch"><img src="<?php echo $this->getViewFileUrl('images/notch.png'); ?>" alt=""> </div>
                                    <div class="p_line"></div>
                                </div>
                                <div class="p_storetitle">
                                    <h2>Store List (<?= count($stores) ?>)</h2>
                                </div>
                                <div class="p_storelistbox">
                                    <?php
                                    $storesCount = 0;
                                    $totalStores = $stores;
                                    $stores = array_slice($stores, 0, $numberofStoresPerPage);
                                    $i=0;
                                    foreach ($stores as $store) {
                                        $i++;
                                        ?>
                                        <?php if ($storesCount >= 5) : ?>
                                        <!--view-more-stores-->
                                            <div class="p_storedetilsbox" id="dealer<?= $store['bajaj_dealerid'] ?>">
                                            <?php else: ?>
                                                <div class="p_storedetilsbox" id="dealer<?= $store['bajaj_dealerid'] ?>">
                                                    <?php
                                                    $storesCount++;
                                                endif;
                                                ?>
                                                <a class="storeName"href="javascript:void(0);">
                                                    <div class="p_nameoffer">
                                                        <div class="p_salesnametitle">
                                                            <h2><?= trim($store['dealer_name']).', ' . $store['area']; ?> </h2>
                                                        </div>
                                                    </div>
                                                    <div class="p_storelistdeta">
                                                        <div class="a_adddisc">
                                                            <p><?= $block->getDealerOffer($store['bajaj_dealerid']) ?></p>
                                                        </div>
                                                    </div>
                                                </a>
                                                <div class="p_knowmore">
                                                    <ul>
                                                        <li class="p_btnknow">
                                                            <a href="javascript:void(0);" class="getdirection listGetDirection" data-lat="<?= $store['latitude'] ?>" data-long="<?= $store['longitude'] ?>">
                                                                <img src="<?php echo $this->getViewFileUrl('images/ico-directio.png'); ?>" alt="">
                                                                <p><?= __('Get Directions') ?></p>
                                                            </a>
                                                        </li>
                                                        <li class = "p_phone">
                                                            <a href="javascript:void(0);">
                                                                <img src = "<?php echo $this->getViewFileUrl('images/ico-call-wht.svg'); ?>" alt = "phone-forwarded">
                                                                <p><?= __('Contact Store') ?></p>
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </div>
                                                <div class="a_continuSdop">
                                                    <div class="a_continuSdopBlack">
                                                        <div class="a_continuPopCon">
                                                            <div class="a_title">
                                                                <h4><?= $store['dealer_name'] . ', ' . $store['area']; ?></h4>
                                                            </div>
                                                            <div class="a_mainCcOn">
                                                                <p>A callback request has been sent to the store. A representative will be calling you shortly</p>
                                                                <a href="<?= $block->getBaseUrl() ?>">Continue Shopping</a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class = "a_storeLList">
                                                    <div class = "a_storeLBlack">
                                                        <div class = "a_continuPopCon">
                                                            <div class = "a_title">
                                                                <h4><?= __('Contact') ?></h4>
                                                            </div>
                                                            <div class = "a_callAndreq">
                                                                <ul>
                                                                    <li>
                                                                        <a href = "tel:<?= $store['phone'] ?>" class = "callStore">
                                                                            <img src = "<?php echo $this->getViewFileUrl('images/ico-call.svg'); ?>" alt = "">
                                                                            <h4><?= __('Call Store') ?></h4>
                                                                            <p><?= __('For a better experience, call from your registered number') ?></p>
                                                                        </a>
                                                                    </li>
                                                                    <?php 
                                                                    if($store['sfdc'] || $sfdc) {  ?>
                                                                    <li>
                                                                        <a href="javascript:void(0);" id="callBack" class="callBack" data-storeid="<?= $store['dealer_id']?>">
                                                                            <img src = "<?php echo $this->getViewFileUrl('images/ico-call-request.svg'); ?>" alt = "">
                                                                            <h4><?= __('Request a Callback') ?></h4>
                                                                            <p><?= __('Get a call from this store') ?></p>
                                                                        </a>
                                                                    </li>
                                                                    <?php } ?>
                                                                </ul>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <?php
                                        }
                                        ?>
                                        <?php if(count($totalStores) > $numberofStoresPerPage):?>
                                        <div class="show_more buttonPart" data-lastid="<?php echo $i; ?>" id="id-<?php echo $i; ?>">
                                          <a href="javascript:void(0);" id="stores-view-more"><?= __('Explore other stores') ?></a>
                                        </div>
                                        <?php endif; ?>                                        
                                    </div>
                                </div>
                            <?php } ?>
                        </div>

                        <div class="a_storfilteropen">
                            <img src="<?php echo $this->getViewFileUrl('images/filter.svg'); ?>" alt="">
                        </div>
                        <div class="p_storelistbg"></div>
                        <div class="mappindetailbox">
                            <div class="storehead">
                                <p>
                                    <img src="<?php echo $this->getViewFileUrl('images/back.svg'); ?>" alt=""><?= __('Map view') ?>
                                </p>
                            </div>
                            <div class="desktopbacklist">
                                <p>
                                    <img src="<?php echo $this->getViewFileUrl('images/back_black.svg'); ?>" alt=""><?= __('Back to list view') ?>
                                </p>
                            </div>
                        </div>
                        <!--store-list-end-->
                    </div>                
                <div class="storelocatorRight storelocatorRightFull">
                    <div class="fullmainmap" id="googleMap"> </div>
                </div>
            </div>
        </section>                    
                <?php } else { ?>
                 </div>                
                <div class="storelocatorRight storelocatorRightFull">
                    <div class="fullmainmap" id="googleMap"> </div>
                </div>
            </div>
        </section> 
                <?php }
                ?>
               
        <div class="newFilterBlack"></div>
        <div class="a_newFilter Storefilter">
            <form id="filter" name="filter" action="#" method="post">
                <div class="fitlerHear">
                    <img src="<?php echo $this->getViewFileUrl('images/closesim.png'); ?>" alt="">
                </div>
                <div class="a_filterCity">
                    <div class="searchbarBox">
                        <i class="fa fa-search"></i>
                        <input type="text" name="city" id="selected-city" placeholder="Search for your city " autocomplete="none">
                        <p class="seachlocationIcon choose-city">
                            <img src="<?php echo $this->getViewFileUrl('images/location.svg'); ?>" alt="location">
                        </p>
                    </div>
                </div>
                <div class="allcitybox">
                    <ul class="allcityUl" id="filtercityul">
                        <?php
                        foreach ($cities as $city) {
                            ?>
                            <li><a href="javascript:void(0);" class="city" data-lat="<?= $city['city_latitude'] ?>" data-long="<?= $city['city_longitude'] ?>" data-city="<?= $city['city_name'] ?>"><?= $city['city_name'] ?> </a></li>
                        <?php }
                        ?>
                    </ul>
                </div>

                <div class="a_filterConmain a_filterConmainShow" id="FilterBY">
                    <div class="a_mainfilBlock">
                        <div class="a_filterAccr" id="a_bransfil">
                            <p>
                                <img src="<?php echo $this->getViewFileUrl('images/catagory.svg'); ?>" alt=""> <?= __('Categories') ?>
                            </p>
                            <i class="fa fa-angle-down"></i>
                        </div>
                        <div class="a_filterCon">
                            <div class="searchPart">
                                <input type="text" placeholder="Search Categories">
                                <button><img src="<?php echo $this->getViewFileUrl('images/search.svg'); ?>" alt=""></button>
                            </div>
                            <ul class="grayCheck">
                                <?php
                                $childrenCategories;
                                $categoryCount = 0;
                                foreach ($categories as $category) {
                                    if (!$category->getIsActive()) {
                                        continue;
                                    }
                                    if ($childrenCategories = $block->getChildCategories($category)) {
                                        foreach ($childrenCategories as $childrenCategory) {
                                            if (!$childrenCategory->getIsActive()) {
                                                continue;
                                            }
                                            $categoryData = $block->getCategory($childrenCategory->getId());
                                            ?>
                                            <?php if ($categoryCount >= 3) : ?>
                                                <li class="view-more-categories">
                                                <?php else : ?>
                                                <li>
                                                <?php endif; ?>
                                                <p>
                                                    <input type="checkbox" id="<?= $childrenCategory->getId() ?>" value="<?= $childrenCategory->getId() ?>" name="category[]" <?php if(in_array($childrenCategory->getId(), $customerData['category_filter'])) { echo 'checked="checked"'; } ?>/>
                                                    <label for="<?= $childrenCategory->getId() ?>"><?= $childrenCategory->getName() ?></label>
                                                </p>
                                            </li>
                                            <?php
                                            $categoryCount++;
                                        }
                                    }
                                }
                                ?>
                            </ul>
                            <div class="category-view-more">
                                <?php if ((($categoryCount) - 3) > 0) : ?>
                                    <p id="category-count"><?= (($categoryCount) - 3) > 0 ? ($categoryCount) - 3 : 0 ?>
                                        <?= /* @escapeNotVerified */ __('more categories') ?>
                                    </p>
                                    <a href="javascript:void(0);" id="view-categories" class="seeMore"><?= /* @escapeNotVerified */ __('View All') ?></a>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                    <?php
                    $dealers = $block->getCurrentCityDealerGroup();
                    ?>
                    <div class="a_mainfilBlock">
                        <div class="a_filterAccr">
                            <p><img src="<?php echo $this->getViewFileUrl('images/store.svg'); ?>" alt=""> <?= __('Stores') ?></p><i class="fa fa-angle-down"></i>
                        </div>
                        <div class="a_filterCon">
                            <div class="searchPart">
                                <input type="text" placeholder="Search Dealers">
                                <button>
                                    <img src="<?php echo $this->getViewFileUrl('images/search.svg'); ?>" alt="">
                                </button>
                            </div>
                            <ul class="grayCheck term-list" id="groupsList">
                                <?php
                                $dealersCount = 0;
                                foreach ($dealers as $dealer) {
                                    ?>
                                    <?php if ($dealersCount >= 5) : ?>
                                        <li class="view-more-dealers">
                                        <?php else : ?>
                                        <li>
                                            <?php
                                            $dealersCount++;
                                        endif;
                                        ?>
                                        <p>
                                            <input type = "checkbox" id = "<?= $dealer['group_id'] ?>" value = "<?= $dealer['group_id'] ?>" name="group[]" <?php if(in_array($dealer['group_id'], $customerData['group_filter'])) { echo 'checked="checked"'; } ?>/>
                                            <label for = "<?= $dealer['group_id'] ?>"><?= $dealer['store_name'] ?></label>
                                        </p>
                                    </li>
                                    <?php
                                }
                                ?>
                            </ul>
                            <div class="dealers-view-more">
                                    <a href="javascript:void(0);" id="view-dealers" class="seeMore">
                                        <p id="dealers-count">
                                            <?= /* @escapeNotVerified */ __('See More') ?>
                                        </p>
                                    </a>
                            </div>
                        </div>
                    </div>

                    <?php
                    $pincodes = $block->getCurrentCityPincode();
                    ?>
                    <div class="a_mainfilBlock">
                        <div class="a_filterAccr">
                            <p><img src="<?php echo $this->getViewFileUrl('images/pincode.svg'); ?>" alt=""> <?= __('Pincode') ?></p><i class="fa fa-angle-down"></i>
                        </div>
                        <div class="a_filterCon">
                            <div class="searchPart">
                                <input type="text" placeholder="Search Pincode">
                                <button><img src="<?php echo $this->getViewFileUrl('images/search.svg'); ?>" alt=""></button>
                            </div>
                            <ul class="grayCheck" id="pincodes">
                                <?php
                                $pincodeCount = 0;
                                foreach ($pincodes as $pincode) {
                                    ?>
                                    <?php if ($pincodeCount >= 5) : ?>
                                        <li class="view-more-pincode">
                                        <?php else : ?>
                                        <li>
                                            <?php
                                            $pincodeCount++;
                                        endif;
                                        ?>
                                        <p>
                                            <input type="radio" id="<?= $pincode['pincode'] ?>" name="pincode" value="<?= $pincode['pincode'] ?>" <?php if($pincode['pincode'] == $customerData['pincode_filter']) { echo 'checked="checked"'; } ?>/>
                                            <label for="<?= $pincode['pincode'] ?>"><?= $pincode['pincode'] ?></label>
                                        </p>
                                    </li>
                                    <?php
                                }
                                ?>
                            </ul>
                            <div class="pincode-view-more">
                                <a href="javascript:void(0);" id="view-pincodes" class="seeMore"><?= /* @escapeNotVerified */ __('See More') ?></a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="buttonDiv">
                    <div class="buttonOne">
                        <a href="javascript:void(0);" class="filterC"><?= __('CLEAR ALL') ?></a>
                    </div>
                    <div class="buttonOne">
                        <a href="javascript:void(0);" class="filterA"><?= __('Apply') ?></a>
                    </div>
                </div>
            </form>
        </div>
    
</div>

<script src='<?php echo $googleMapsApi; ?>'>
</script>
<script type="text/javascript">
    require(['jquery', 'loader'], function ($) {
        $(document).ready(function () { 
             $(document).on('click','.show_more',function(){
                 var lastId = $(this).data('lastid');
                 var divLength=$('.p_storedetilsbox').length;
                 var currentId = $(this).attr('id');
                $.ajax({
                    type:'POST',
                    url:"<?php echo $this->getUrl("storelocator/index/viewmore"); ?>",
                    showLoader:true,
                    data: { lastId: lastId,divlength:divLength },
                    success:function(html){
                        $('.p_storelistbox').append(html);
                        $('[data-role="pannel"]').trigger('hide.loader'); 
                        $('#'+currentId).remove();
                    }
                });
            });
            
<?php
if (isset($customerData['bfl_customer_city_name']) && !empty($customerData['bfl_customer_city_name'])) {
    ?>
                if ($(window).width() > 600) {
                    $('.a_lookingPart').show();
                } else {
                    $('.selectCityBox').addClass('slideleft');
                    $('.a_lookingPart').removeClass('slideright');
                }
<?php } ?>
<?php
if (isset($customerData['categorylob']) && !empty($customerData['categorylob']) && !empty($customerData['bfl_customer_city_name'])) {
    ?>
                if ($(window).width() > 600) {
                    $('.a_lookingPart').hide();
                    $('.p_storelist').show();
                    $('.a_storeListavail').show();
                    $('.storelocatorLeft').removeClass('storelocatorLeftFull');
                } else {
                    $('.a_lookingPart').addClass('slideleft');
                    $('.p_storelist').removeClass('slideright');
                    $('.a_storeListavail').show();
                }
<?php } ?>
        });
    });
</script>